### ISSUE TITLE
Unable to find a matching configuration of project

### ISSUE THREAD

**Issue by khjde1207** [benlui/react-native-region-monitor#1]
Thank you for making a good project!
An error occurs during the build process after installation.
Can you help me?(android)

react-native init testGPS 
cd testGPS 
npm i 
npm install @hkpuits/react-native-region-monitor --save
react-native link
react-native run-android

What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :@hkpuits_react-native-region-monitor.
     Required by:
         project :app
      > Unable to find a matching configuration of project :@hkpuits_react-native-region-monitor: None of the consumable configurations have attributes.

Do you need any other fix after installation?

**Comment by benlui** [comment]
same as original source, for Android, you will need to modify your project android/settings.gradle to point to the correct path

e.g. android/settings.gradle (add **/lib**)
...
include ':@hkpuits_react-native-region-monitor'
project(':@hkpuits_react-native-region-monitor').projectDir = new File(rootProject.projectDir, '../node_modules/@hkpuits/react-native-region-monitor/android/lib')
...
